{"uuid":"b56d11ab-04e4-48f3-8089-407f7e7268cb","historyId":"2b3e8d6e1fc0f057bb2060f5b8b3197","testCaseId":"[engine:junit-jupiter]/[class:ExceptionHandlingTest]/[method:exception()]","testCaseName":"exception()","fullName":"ExceptionHandlingTest.exception","labels":[{"name":"junit.platform.uniqueid","value":"[engine:junit-jupiter]/[class:ExceptionHandlingTest]/[method:exception()]"},{"name":"story","value":"Обработка исключений"},{"name":"host","value":"VNE-NN-22-292"},{"name":"thread","value":"23432@VNE-NN-22-292.main(1)"},{"name":"framework","value":"junit-platform"},{"name":"language","value":"java"},{"name":"package","value":"ExceptionHandlingTest"},{"name":"testClass","value":"ExceptionHandlingTest"},{"name":"testMethod","value":"exception"},{"name":"suite","value":"ExceptionHandlingTest"}],"links":[],"name":"exception()","status":"passed","stage":"finished","description":"Тест на обработку исключений для проверки NullPointerException","steps":[],"attachments":[],"parameters":[],"start":1746931539284,"stop":1746931539304}